from enum import Enum

CHANNELS_NAMES = [
    "New_Vulnerability",
    "itsecforutel",
    "searchinform",
    "dataleak",
    "EchelonEyes",
    "haccking",
    "manual_pentesting",
    "crypto_security_lab",
    "bugfeature",
    "hack_less",
    "true_secator",
    "Social_engineering",
    "vecherniy_danya",
    "tssolution",
    "unidataline",
    "devsecops_weekly",
    "nejdanov",
    "codeby_sec",
    "open_source_friend",
    "matrixleak",
    "Russian_OSINT",
    "cyberyozh_official",
    "news_infosecurity",
    "infowatchout",
    "kasperskylab_ru",
    "xakep_ru",
    "mobile_appsec_world",
    "AnonCyberWarrior",
    "Hacker_of_Algorithms",
    "ALLABOUTHACK",
    "AfrikaHackers",
    "sysadm_in_channel",
    "cibsecurity"
]

OUTPUT_FILE = "channel_threats.json"


class TypeThreatsEnum(str, Enum):
    VULNERABILITY = 'Уязвимость'
    ATTACK = 'Атака'
    INCIDENT = 'Инцидент'
    THREAT = 'Угроза'


class DatabaseIdentifiersThreatsEnum(str, Enum):
    VULNERABILITY = 'Уязвимость'
    THREAT = 'Угроза'


DATABASE_IDENTIFIERS_VULNERABILITIES_KEYWORDS = {
    "CWE",
    "CVE",
    "CIRCL",
    "VulDB",
    "SecurityFocus",
    "40day.today",
    "Rapid7",
    "NIST",
    "Packet Storm Security",
    "Exploit Database",
    "Vulners",
    "MITRE"
}

DATABASE_IDENTIFIERS_THREATS_KEYWORDS = {"ФСТЭК", "SecurityLab"}

VULNERABILITIES_KEYWORDS = {
    "Уязвимости",
    "уязвимость",
    "уязвимостью",
    "уязвимостями",
    "уязвимостях",
    "уязвимостей",
    "уязвимостям",
    "слабое место",
    "слабые места",
    "слабыми местами",
    "слабым местом",
    "слабых местах",
    "слабом месте",
    "слабых местах",
    "слабость",
    "слабости",
    "слабостями",
    "слабостях",
    "слабостям",
    "слабостью",
    "недостаток",
    "недостатки",
    "недостатками",
    "недостатках",
    "недостатком",
    "недостатку",
    "недостатке",
    "CVE",
    "CIRCL",
    "VulDB",
    "SecurityFocus",
    "40day.today",
    "Rapid7",
    "NIST",
    "Packet Storm Security",
    "Exploit Database",
    "Vulners",
    "CVSS",
    "уязвимости нулевого дня",
    "уязвимостью нулевого дня",
    "уязвимость нулевого дня",
    "переполнение буфера",
    "переполнение буферов",
    "эксплойт",
    "подделка запросов",
    "межсайтовый скриптинг",
    "удаленное выполнение кода",
    "обратный инжиниринг",
    "обратным инжинирингом",
    "python",
    "XSS-уязвимость",
    "IDOR-уязвимость",
    "брандмауэр",
    "брандмауэром",
    "брандмауэрами",
    "брандмауэры",
    "эксплуатация",
    "эксплуатации",
    "эксплуатациями",
    "эксплуатацией",
    "Vulnerabilities",
    "vulnerability",
    "weak spot",
    "spot presence",
    "spot detection",
    "detection",
    "weakness",
    "deficiency",
    "disappearance",
    "presence",
    "deficiency",
    "CIRCL",
    "VulDB",
    "SecurityFocus",
    "40day.today",
    "Rapid7",
    "NIST",
    "Packet Storm Security",
    "Exploit Database",
    "Vulners",
    "CVSS",
    "zero-day vulnerabilities",
    "zero-day vulnerability",
    "buffer overflow",
    "exploit",
    "open spoofing",
    "cross site scripting",
    "remote code execution",
    "reverse engineering",
    "python",
    "XSS vulnerability",
    "IDOR vulnerability",
    "firewall",
    "firewalls",
    "exploitation",
    "exploitations"
}

ATTACKS_KEYWORDS = {
    "Атаки",
    "атака",
    "атаку",
    "атаками",
    "атакой",
    "атаке",
    "атак",
    "атака",
    "атаках",
    "CAPEC",
    "MITRE",
    "ATT&CK",
    "ФСТЭК",
    "злоумышленник",
    "злоумышленники",
    "злоумышленником",
    "нарушитель",
    "нарушители",
    "нарушителями",
    "нарушителей",
    "нарушителю",
    "нарушителях",
    "нарушителе",
    "нарушителем",
    "нарушителя",
    "хакер",
    "хакерами",
    "хакера",
    "хакеру",
    "хакере",
    "хакером",
    "хакеров",
    "хакерам",
    "хакерах",
    "жертва",
    "жертвы",
    "жертве",
    "жертвами",
    "жертвой",
    "жертвах",
    "жертвам",
    "жертв",
    "пользователь",
    "пользователей",
    "пользователя",
    "пользователем",
    "пользователю",
    "пользователе",
    "пользователи",
    "пользователем",
    "пользователям",
    "пользователях",
    "фишинг",
    "фишинговая",
    "фишинга",
    "фишингом",
    "DDoS",
    "DoS",
    "Brute-force",
    "SQL-инъекция",
    "таргетированная атака",
    "таргетированной атакой",
    "целевая атака",
    "целевой атакой",
    "APT",
    "сетевая атака",
    "сетевой атакой",
    "шпионское ПО",
    "шпионским ПО",
    "касперский",
    "код безопасности",
    "код безопасностью",
    "InfoWatch",
    "Кибер",
    "киберсистема",
    "киберфизическая",
    "киберпреступник",
    "кибератака",
    "киберпространоство",
    "киберсталкинг",
    "взлом",
    "шифрование",
    "шифр",
    "шифровальщик",
    "безопасность",
    "безопасности",
    "перехват",
    "перехватывают",
    "перехватили",
    "перехватить",
    "вирус",
    "вирусы",
    "Attacks",
    "attacks",
    "CAPEC",
    "MITER",
    "ATT&CK",
    "FSTEC",
    "commitment",
    "ban",
    "violator",
    "hackers",
    "hacker",
    "victim",
    "user",
    "users",
    "favor",
    "phishing",
    "ddos",
    "dos",
    "brute-force",
    "SQL injection",
    "targeted attack",
    "attack detection",
    "APT",
    "network attack",
    "spyware",
    "kaspersky",
    "security code",
    "InfoWatch",
    "cyber",
    "cyber system",
    "cyber physical",
    "cyber criminal",
    "cyberattack",
    "cyberspace",
    "cyberstalking",
    "hacking",
    "encryption",
    "cipher",
    "ransomware",
    "security",
    "safety",
    "intercept",
    "virus",
    "viruses"
}

INCIDENTS_KEYWORDS = {
    "Инцидент",
    "инциденты",
    "инцидентов",
    "инцидентом",
    "инциденту",
    "инциденте",
    "инцидентам",
    "инцидентами",
    "инцидентах",
    "информационная безопасность",
    "информационной безопасностью",
    "реагирование",
    "реагирования",
    "реагированию",
    "реагированием",
    "реагировании",
    "реагирований",
    "реагированиями",
    "реагированиям",
    "реагированиях",
    "последствия",
    "последствием",
    "последствию",
    "последствии",
    "последствий",
    "последствиям",
    "последствиями",
    "последствиях",
    "ущерб",
    "ущерба",
    "ущербом",
    "ущербу",
    "ущербе",
    "ущербов",
    "ущербами",
    "ущербах",
    "нежелательное событие",
    "нежелательные события",
    "потеря",
    "потерь",
    "потерей",
    "потери",
    "потерям",
    "потерями",
    "потерях",
    "причины",
    "причина",
    "следствие",
    "следствий",
    "следствием",
    "мошенник",
    "мошенника",
    "мошенником",
    "мошеннику",
    "мошенником",
    "мошенники",
    "мошенников",
    "мошенникам",
    "мошенниками",
    "мошенников",
    "утечка",
    "утечки",
    "утечками",
    "данные",
    "данных",
    "мониторинг",
    "мониторить",
    "мониторят",
    "снифер",
    "сниферы",
    "сниферами ",
    "Incident",
    "merged",
    "incidents",
    "information security",
    "security disclosure",
    "response",
    "acute state",
    "response",
    "feeling",
    "value",
    "consequences",
    "consequence",
    "loss",
    "losses",
    "causes",
    "consequences",
    "scammer",
    "scammers",
    "leaks",
    "data",
    "monitor",
    "sniffer",
    "sniffers"
}

THREATS_KEYWORDS = {
    'Угрозы',
    'угроза',
    'угрозами',
    'угрозой',
    'угрозе',
    'угроз',
    'угрозам',
    'угрозах',
    'CWE',
    'CWSS',
    'SecurityLab',
    'внутренняя угроза',
    'внутренней угрозой',
    'внутренними угрозами',
    'внешняя угроза',
    'внешней угрозой',
    'опасность',
    'опасности',
    'опасностью',
    'опасностей',
    'опасностями',
    'опасностям',
    'опасностях',
    'информационная система',
    'информационной системой',
    'автоматизированная система',
    'автоматизированной системы',
    'информационные ресурсы',
    'информационный ресурс',
    'искажение',
    'искажения',
    'искажении',
    'искажению',
    'искажении',
    'искажений',
    'искажениями',
    'искажениям',
    'искажениях',
    'несанкционированный',
    'несанкционированная',
    'несанкционированной',
    'несанкционированными',
    'модификация',
    'модификации',
    'модификацией',
    'модификациями',
    'модификациям',
    'модификациях',
    'разрушение',
    'разрушения',
    'разрушением',
    'разрушению',
    'разрушении',
    'разрушений',
    'разрушениями',
    'разрушениям',
    'разрушениях',
    'дестабилизация',
    'дестабилизации',
    'дестабилизацией',
    'дестабилизации',
    'дестабилизаций',
    'дестабилизациям',
    'дестабилизациями',
    'дестабилизациях',
    'нарушение',
    'нарушения',
    'нарушение',
    'нарушению',
    'нарушением',
    'нарушении',
    'нарушений',
    'нарушениями',
    'нарушениям',
    'нарушениях',
    'реализация',
    'реализации',
    'реализацией',
    'реализациями',
    'реализациях',
    'реализациям',
    'Threat',
    'threats',
    'CWE',
    'CWSS',
    'SecurityLab',
    'internal threat',
    'external threat',
    'danger',
    'fear',
    'information system',
    'internal system',
    'information resou  {rces',
    'distortion',
    'unauthorized',
    'modification',
    'modifications',
    'destruction',
    'violations',
    'destabilization',
    'violation',
    'violation of implementation',
    'implementation',
    'implementations'
}

KEYWORDS = {
    *DATABASE_IDENTIFIERS_VULNERABILITIES_KEYWORDS,
    *DATABASE_IDENTIFIERS_THREATS_KEYWORDS,
    *VULNERABILITIES_KEYWORDS,
    *ATTACKS_KEYWORDS,
    *INCIDENTS_KEYWORDS,
    *THREATS_KEYWORDS,
}

UNIQUE_KEYWORDS = list(set(KEYWORDS))

KEYWORD_DATABASE_IDENTIFIERS_PAIRS = [
    (DATABASE_IDENTIFIERS_THREATS_KEYWORDS, DatabaseIdentifiersThreatsEnum.THREAT.value),
    (DATABASE_IDENTIFIERS_VULNERABILITIES_KEYWORDS, DatabaseIdentifiersThreatsEnum.VULNERABILITY.value),
]

KEYWORD_THREAT_TYPE_PAIRS = [
    (VULNERABILITIES_KEYWORDS, TypeThreatsEnum.VULNERABILITY.value),
    (ATTACKS_KEYWORDS, TypeThreatsEnum.ATTACK.value),
    (INCIDENTS_KEYWORDS, TypeThreatsEnum.INCIDENT.value),
    (THREATS_KEYWORDS, TypeThreatsEnum.THREAT.value)
]

FIELD_TYPE = 'type'
FIELD_DATABASE_IDENTIFIERS = 'database_identifiers'
